POST http://localhost:8080/Graveyard/Init

###

GET http://localhost:8080/Graveyard/ReadGravestones
Accept: application/json

###

POST http://localhost:8080/Graveyard/Create
Content-Type:application/json

{
  "Id": 5,
  "dateofdeath": "2017-05-22",
  "name": "John Baker"
}

###

DELETE http://localhost:8080/Graveyard/Delete/3

###

PUT http://localhost:8080/Graveyard/Put
Content-Type:application/json

{
  "id": 3,
  "dateofdeath" : "2020-03-21",
  "name" : "Brunhilde Degredandus"
}

###